<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>app_icon.ico</ApplicationIcon>
    <RootNamespace>BCCScreenShot</RootNamespace>
    <AssemblyName>BCCScreenShot</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="9.0.2" />
  </ItemGroup>
</Project>
